-- MySQL Script generated by MySQL Workbench
-- 01/14/17 13:40:33
-- Model: conkan    Version: 1.2.1

-- コンベンション管理システム

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema conkan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `conkan` ;

-- -----------------------------------------------------
-- Schema conkan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conkan` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `conkan` ;

-- -----------------------------------------------------
-- Table `conkan`.`pg_system_conf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_system_conf` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_system_conf` (
  `pg_conf_code` VARCHAR(64) NOT NULL,
  `pg_conf_name` VARCHAR(64) NOT NULL,
  `pg_conf_value` TEXT NOT NULL,
  PRIMARY KEY (`pg_conf_code`))
ENGINE = InnoDB
COMMENT = 'Define value for THIS convention';


-- -----------------------------------------------------
-- Table `conkan`.`pg_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_staff` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_staff` (
  `StaffID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `account` VARCHAR(64) NOT NULL,
  `passwd` VARCHAR(64) NULL DEFAULT NULL,
  `role` ENUM('NORM','ROOT','PG','ADMIN') NOT NULL,
  `ma` VARCHAR(64) NULL DEFAULT NULL,
  `telno` VARCHAR(64) NULL DEFAULT NULL,
  `regno` VARCHAR(64) NULL DEFAULT NULL,
  `tname` VARCHAR(64) NULL DEFAULT NULL,
  `tnamef` VARCHAR(64) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `otherUID` TEXT NULL DEFAULT NULL,
  `lastlogin` DATETIME NULL DEFAULT NULL,
  `updateflg` VARCHAR(64) NULL DEFAULT NULL,
  `rmdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`StaffID`),
  INDEX `account_key` (`account` ASC),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC))
ENGINE = InnoDB
COMMENT = 'staff info';


-- -----------------------------------------------------
-- Table `conkan`.`pg_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_room` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_room` (
  `RoomID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `roomNo` VARCHAR(64) NOT NULL,
  `max` INT NULL DEFAULT NULL,
  `type` VARCHAR(64) NOT NULL,
  `size` INT NULL DEFAULT NULL,
  `tablecnt` INT NULL DEFAULT NULL,
  `chaircnt` INT NULL DEFAULT NULL,
  `equips` VARCHAR(64) NULL DEFAULT NULL,
  `useabletime` VARCHAR(64) NULL DEFAULT NULL,
  `net` ENUM('NONE','W','E') NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `updateflg` VARCHAR(64) NULL DEFAULT NULL,
  `rmdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`RoomID`),
  INDEX `roomNo_key` (`roomNo` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `roomNo_UNIQUE` (`roomNo` ASC))
ENGINE = InnoDB
COMMENT = 'room info';


-- -----------------------------------------------------
-- Table `conkan`.`pg_all_equip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_all_equip` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_all_equip` (
  `EquipID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `equipNo` VARCHAR(64) NOT NULL,
  `spec` VARCHAR(64) NULL DEFAULT NULL,
  `RoomId` INT UNSIGNED NULL DEFAULT NULL,
  `comment` VARCHAR(64) NULL DEFAULT NULL,
  `suppliers` VARCHAR(64) NULL DEFAULT NULL,
  `updateflg` VARCHAR(64) NULL DEFAULT NULL,
  `rmdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`EquipID`),
  INDEX `equipNo_key` (`equipNo` ASC),
  UNIQUE INDEX `equipNo_UNIQUE` (`equipNo` ASC),
  INDEX `RoomID_idx` (`RoomId` ASC),
  CONSTRAINT `RoomID`
    FOREIGN KEY (`RoomId`)
    REFERENCES `conkan`.`pg_room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'all equipment info';


-- -----------------------------------------------------
-- Table `conkan`.`pg_reg_program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_reg_program` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_reg_program` (
  `regPgID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `namef` VARCHAR(64) NOT NULL,
  `regdate` DATE NOT NULL,
  `regname` VARCHAR(64) NOT NULL,
  `regMa` VARCHAR(64) NOT NULL,
  `regno` VARCHAR(64) NOT NULL,
  `telno` VARCHAR(64) NULL DEFAULT NULL,
  `faxno` VARCHAR(64) NULL DEFAULT NULL,
  `celno` VARCHAR(64) NULL DEFAULT NULL,
  `type` VARCHAR(64) NOT NULL,
  `place` VARCHAR(64) NOT NULL,
  `layout` VARCHAR(64) NOT NULL,
  `date` VARCHAR(64) NOT NULL,
  `classLen` VARCHAR(64) NOT NULL,
  `expMaxcnt` VARCHAR(64) NOT NULL,
  `content` TEXT NOT NULL,
  `contentPub` VARCHAR(64) NOT NULL,
  `realPub` VARCHAR(64) NOT NULL,
  `afterPub` VARCHAR(64) NOT NULL,
  `openPg` VARCHAR(64) NOT NULL,
  `restPg` VARCHAR(64) NOT NULL,
  `avoidDup` TEXT NULL DEFAULT NULL,
  `experience` VARCHAR(64) NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `updateflg` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`regPgID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5001
COMMENT = 'program registration data';


-- -----------------------------------------------------
-- Table `conkan`.`pg_reg_cast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_reg_cast` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_reg_cast` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `regPgID` INT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `namef` VARCHAR(64) NULL DEFAULT NULL,
  `title` VARCHAR(64) NULL DEFAULT NULL,
  `entrantRegNo` VARCHAR(64) NULL DEFAULT NULL,
  `needReq` VARCHAR(64) NULL DEFAULT NULL,
  `needGuest` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `regPgId_fkey_idx` (`regPgID` ASC),
  CONSTRAINT `reg_cast_regPgId_fkey`
    FOREIGN KEY (`regPgID`)
    REFERENCES `conkan`.`pg_reg_program` (`regPgID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'cast registration data';


-- -----------------------------------------------------
-- Table `conkan`.`pg_reg_equip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_reg_equip` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_reg_equip` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `regPgID` INT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `count` INT UNSIGNED NULL DEFAULT 1,
  `vIF` VARCHAR(64) NULL DEFAULT NULL,
  `aIF` VARCHAR(64) NULL DEFAULT NULL,
  `eIF` VARCHAR(64) NULL DEFAULT NULL,
  `intendE` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `regPgID_fkey_idx` (`regPgID` ASC),
  CONSTRAINT `reg_equip_regPgID_fkey`
    FOREIGN KEY (`regPgID`)
    REFERENCES `conkan`.`pg_reg_program` (`regPgID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'equipment registration data';


-- -----------------------------------------------------
-- Table `conkan`.`pg_program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_program` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_program` (
  `PgID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `regPgID` INT UNSIGNED NOT NULL,
  `sname` VARCHAR(64) NULL DEFAULT NULL,
  `subno` INT UNSIGNED NULL DEFAULT 0,
  `StaffID` INT UNSIGNED NULL DEFAULT NULL,
  `status` VARCHAR(64) NULL DEFAULT NULL,
  `memo` TEXT NULL DEFAULT NULL,
  `date1` DATE NULL DEFAULT NULL,
  `stime1` TIME NULL DEFAULT NULL,
  `etime1` TIME NULL DEFAULT NULL,
  `date2` DATE NULL DEFAULT NULL,
  `stime2` TIME NULL DEFAULT NULL,
  `etime2` TIME NULL DEFAULT NULL,
  `RoomID` INT UNSIGNED NULL,
  `LayerNo` INT NULL DEFAULT 0,
  `progressPrp` TEXT NULL DEFAULT NULL,
  `updateflg` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`PgID`),
  INDEX `regPgID_fkey_idx` (`regPgID` ASC),
  INDEX `StaffID_fkey_idx` (`StaffID` ASC),
  INDEX `RoomID_fkey_idx` (`RoomID` ASC),
  CONSTRAINT `program_regPgID_fkey`
    FOREIGN KEY (`regPgID`)
    REFERENCES `conkan`.`pg_reg_program` (`regPgID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `program_StaffID_fkey`
    FOREIGN KEY (`StaffID`)
    REFERENCES `conkan`.`pg_staff` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `program_RoomID_fkey`
    FOREIGN KEY (`RoomID`)
    REFERENCES `conkan`.`pg_room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = 'Program Management Master';


-- -----------------------------------------------------
-- Table `conkan`.`pg_progress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_progress` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_progress` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `regPgID` INT UNSIGNED NOT NULL,
  `StaffID` INT UNSIGNED NOT NULL,
  `repDateTime` DATETIME NOT NULL,
  `report` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `regPgID_fkey_idx` (`regPgID` ASC),
  INDEX `StaffID_fkey_idx` (`StaffID` ASC),
  CONSTRAINT `progress_regPgID_fkey`
    FOREIGN KEY (`regPgID`)
    REFERENCES `conkan`.`pg_reg_program` (`regPgID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `progress_StaffID_fkey`
    FOREIGN KEY (`StaffID`)
    REFERENCES `conkan`.`pg_staff` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Progress data';


-- -----------------------------------------------------
-- Table `conkan`.`pg_all_cast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_all_cast` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_all_cast` (
  `CastID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `regno` VARCHAR(64) NULL,
  `name` VARCHAR(64) NOT NULL,
  `namef` VARCHAR(64) NULL DEFAULT NULL,
  `status` VARCHAR(64) NULL DEFAULT NULL,
  `memo` TEXT NULL DEFAULT NULL,
  `restdate` TEXT NULL DEFAULT NULL,
  `updateflg` VARCHAR(64) NULL DEFAULT NULL,
  `rmdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`CastID`),
  UNIQUE INDEX `regno_UNIQUE` (`regno` ASC))
ENGINE = InnoDB
COMMENT = 'All cast data';


-- -----------------------------------------------------
-- Table `conkan`.`pg_cast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_cast` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_cast` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PgID` INT UNSIGNED NOT NULL,
  `CastID` INT UNSIGNED NOT NULL,
  `status` VARCHAR(64) NULL DEFAULT NULL,
  `memo` TEXT NULL DEFAULT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `namef` VARCHAR(64) NULL DEFAULT NULL,
  `title` VARCHAR(64) NULL DEFAULT NULL,
  `updateflg` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `CastID_fkey_idx` (`CastID` ASC),
  INDEX `cast_PgID_fkey_idx` (`PgID` ASC),
  CONSTRAINT `cast_PgID_fkey`
    FOREIGN KEY (`PgID`)
    REFERENCES `conkan`.`pg_program` (`PgID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cast_CastID_fkey`
    FOREIGN KEY (`CastID`)
    REFERENCES `conkan`.`pg_all_cast` (`CastID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Cast Management master';


-- -----------------------------------------------------
-- Table `conkan`.`pg_equip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`pg_equip` ;

CREATE TABLE IF NOT EXISTS `conkan`.`pg_equip` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PgID` INT UNSIGNED NOT NULL,
  `EquipID` INT UNSIGNED NULL DEFAULT NULL,
  `vif` VARCHAR(64) NULL DEFAULT NULL,
  `aif` VARCHAR(64) NULL DEFAULT NULL,
  `eif` VARCHAR(64) NULL DEFAULT NULL,
  `intendE` VARCHAR(64) NULL DEFAULT NULL,
  `updateflg` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `EquipID_fkey_idx` (`EquipID` ASC),
  INDEX `equip_PgID_fkey_idx` (`PgID` ASC),
  CONSTRAINT `equip_PgID_fkey`
    FOREIGN KEY (`PgID`)
    REFERENCES `conkan`.`pg_program` (`PgID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `equip_EquipID_fkey`
    FOREIGN KEY (`EquipID`)
    REFERENCES `conkan`.`pg_all_equip` (`EquipID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Equipment Management master';


-- -----------------------------------------------------
-- Table `conkan`.`login_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conkan`.`login_log` ;

CREATE TABLE IF NOT EXISTS `conkan`.`login_log` (
  `logID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `StaffID` INT UNSIGNED NOT NULL,
  `login_date` DATETIME NOT NULL,
  INDEX `logID_index` (`logID` ASC),
  INDEX `StaffID_idx` (`StaffID` ASC),
  PRIMARY KEY (`logID`),
  CONSTRAINT `StaffID`
    FOREIGN KEY (`StaffID`)
    REFERENCES `conkan`.`pg_staff` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
